### ISSUE TITLE
Could you compile Dosbox-X on the RetroFW platform？

### ISSUE THREAD

**Issue by KatyushaScarlet** [jbanes/rs97-dosbox#1]
Compared to the Dosbox, [Dosbox-X](https://github.com/joncampbell123/dosbox-x) can run on PC-98 mode.
And [Dosbox-X](https://github.com/joncampbell123/dosbox-x) works better than Neko Project II with some PC-98 games (for example, touhou 01~05).
Thank you for your reply :)

**Comment by jbanes** [comment]
Sorry for the delay Still figuring out some of the features of GitHub. I have no plans to port DOSBox-X at this time. As it stands, I'm still working to understand a lot of the internals of DOSBox. The version I have (which was kindly ported by someone else in the past) has enough things to sort out that I don't want to try a fresh port at this time. 

Maybe in the future. But I wouldn't hold your breath for it being soon. Sorry!
