### ISSUE TITLE
dosbox mapper

### ISSUE THREAD

**Issue by pppgamer** [jbanes/rs97-dosbox#2]
Hello,

Looks like the dosbox mapper freezes when I attempt to start it on my device. 

Is it possible that someone can share the button strings that can be used in the a referenced mapperfile I can't seem to find it in the source.

Thanks.

**Comment by jbanes** [comment]
Sorry for the delay! Still figuring out some of the features of GitHub. 

The long and short of it is that the key handling is hardcoded in the current version. (I inherited it that way.) Don't count on that changing anytime soon as DOSBox is configured in direct mode. i.e. It's passing the key codes from the buttons directly through. (Yes, the buttons really are mapped to left alt, left shift, enter, escape, etc.) In result, the key mapper is more or less disabled as it's not useful right now. Thanks for the question, though!
